### PR TITLE
bump bn-js

### PR DESCRIPTION
**Pull request by calvinmetcalf**
part of crypto-browserify/crypto-browserify#140 waiting on crypto-browserify/parse-asn1#16

### CODE REVIEW

**Comment by dcousens** [comment]
:+1:

**Comment by dcousens** [comment]
Not published (but you may publish it if necessary)

**Comment by calvinmetcalf** [comment]
we missed a dev dep on this one so I pushed that up to master (not publishing it because it's only a dev)

**Comment by dcousens** [comment]
ACK

**Pull request merged**
